### ISSUE TITLE
Compile error on 0.4.6

### ISSUE THREAD

**Issue by praveenperera** [pow-auth/pow_assent#150]
Pow - 1.0.18
PowAssent - 0.4.6

```
== Compilation error in file lib/pow_assent/store/session.ex ==
** (CompileError) lib/pow_assent/store/session.ex:5: module Pow.Store.Base is not loaded and could not be found
    (elixir 1.10.1) expanding macro: Kernel.use/2
    lib/pow_assent/store/session.ex:5: PowAssent.Store.SessionCache (module)
    (elixir 1.10.1) lib/kernel/parallel_compiler.ex:233: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```

Works when I downgrade to 0.4.5

What I've tried so far

1. `rm -rf deps` and get `mix deps.get`

**Comment by danschultzer** [comment]
Try clear the dependencies and compile again with `mix deps.clean --all && mix deps.get && mix deps.compile`. `Pow.Store.Base` has been a part of Pow since the beginning so this is really weird.

**Comment by praveenperera** [comment]
This is weird I did:  `mix deps.clean --all && mix deps.get && mix deps.compile`

And I got it:

```bash
== Compilation error in file lib/extensions/email_confirmation/ecto/schema.ex ==
** (CompileError) lib/extensions/email_confirmation/ecto/schema.ex:29: module Pow.Extension.Ecto.Schema.Base is not loaded and could not be found
    (elixir 1.10.1) expanding macro: Kernel.use/1
    lib/extensions/email_confirmation/ecto/schema.ex:29: PowEmailConfirmation.Ecto.Schema (module)
    (elixir 1.10.1) lib/kernel/parallel_compiler.ex:233: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```

**Comment by praveenperera** [comment]
Doing 

```
rm -rf deps && mix deps.clean --all && mix deps.get && mix deps.compile
```

Worked...

**Comment by danschultzer** [comment]
Great! I believe this is unrelated to Pow, and it’s the Elixir dependency handling/compilation that acts up. I’ve seen it occasionally with other libs too.

**Comment by praveenperera** [comment]
Yes I think you are right, sorry about that.

**Comment by danschultzer** [comment]
No worries!
