### ISSUE TITLE
Translate provider_links button with gettext

### ISSUE THREAD

**Issue by gilbertobr** [pow-auth/pow_assent#184]
It would be possible to translate this button with gettext

```
<%= for link <- PowAssent.Phoenix.ViewHelpers.provider_links(@conn),
  do: content_tag(:span,  link) %>
```

How would it be?
Are there other ways to translate?

**Comment by danschultzer** [comment]
Yeah, it's described here: https://hexdocs.pm/pow_assent/0.4.8/README.html#i18n

The messages can be found here (the one you are looking for is `login_with_provider` and `remove_provider_authentication`, the provider is found in `conn.params["provider"]`): https://hexdocs.pm/pow_assent/0.4.8/PowAssent.Phoenix.Messages.html#content

**Comment by gilbertobr** [comment]
Whenever I add login_with_provider (conn), it returns this error.

Would you help me?

```
  def pow_assent_login_with_provider(conn) do
    provider = Phoenix.Naming.humanize(conn.params["provider"])
    gettext("Sign in with %{provider}", provider)
  end
```

Error:

```
* (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Gettext.dpgettext/5
        (gettext) lib/gettext.ex:701: Gettext.dpgettext(TestWeb.Gettext, "default", nil, "Sign in with %{provider}", "Google")
        (pow_assent) lib/pow_assent/phoenix/views/view_helpers.ex:44: PowAssent.Phoenix.ViewHelpers.authorization_link/3
        (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
        (teste) lib/teste_web/templates/pow/session/new.html.eex:95: anonymous fn/2 in TesteWeb.Pow.SessionView."new.html"/1
        (phoenix_html) lib/phoenix_html/form.ex:372: Phoenix.HTML.Form.form_for/4
        (teste) lib/teste_web/templates/pow/session/new.html.eex:60: TesteWeb.Pow.SessionView."new.html"/1
        (teste) lib/teste_web/templates/layout/app.html.eex:35: TesteWeb.LayoutView."app.html"/1
        (phoenix) lib/phoenix/view.ex:410: Phoenix.View.render_to_iodata/3
        (phoenix) lib/phoenix/controller.ex:729: Phoenix.Controller.__put_render__/5
        (phoenix) lib/phoenix/controller.ex:746: Phoenix.Controller.instrument_render_and_send/4
        (pow) lib/pow/phoenix/controllers/session_controller.ex:1: Pow.Phoenix.SessionController.action/2
        (pow) lib/pow/phoenix/controllers/session_controller.ex:1: Pow.Phoenix.SessionController.phoenix_controller_pipeline/2
  ...
```
