### ISSUE TITLE
Phoenix.HTML.Link removed

### ISSUE THREAD

**Issue by xanderio** [pow-auth/pow_assent#247]
With [Phoenix.HTML version 4.0.0](https://hexdocs.pm/phoenix_html/4.0.0/changelog.html#v4-0-0-2023-12-19) the `Phoenix.HTML.Link` module was removed. This causes the functions in `PowAssent.Phoenix.ViewHelpers` to fail.

```
[error] GenServer #PID<0.1237.0> terminating
** (UndefinedFunctionError) function Phoenix.HTML.Link.link/2 is undefined (module Phoenix.HTML.Link is not available)
    Phoenix.HTML.Link.link("Remove Oidc authentication", [to: "/auth/oidc", method: :delete])
    (albert 0.1.0) lib/albert_web/controllers/page_html/home.html.heex:2: anonymous fn/2 in AlbertWeb.PageHTML.home/1
    (phoenix_live_view 0.20.4) lib/phoenix_live_view/engine.ex:150: Phoenix.HTML.Safe.Phoenix.LiveView.Rendered.to_iodata/1
    (phoenix_live_view 0.20.4) lib/phoenix_live_view/engine.ex:166: Phoenix.HTML.Safe.Phoenix.LiveView.Rendered.to_iodata/3
    (phoenix 1.7.11) lib/phoenix/controller.ex:1008: anonymous fn/5 in Phoenix.Controller.template_render_to_iodata/4
    (telemetry 1.2.1) /Users/xanderio/dev/cyberus/albert/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
    (phoenix 1.7.11) lib/phoenix/controller.ex:974: Phoenix.Controller.render_and_send/4
    (albert 0.1.0) lib/albert_web/controllers/page_controller.ex:1: AlbertWeb.PageController.action/2
    (albert 0.1.0) lib/albert_web/controllers/page_controller.ex:1: AlbertWeb.PageController.phoenix_controller_pipeline/2
    (phoenix 1.7.11) lib/phoenix/router.ex:484: Phoenix.Router.__call__/5
    (albert 0.1.0) lib/albert_web/endpoint.ex:1: AlbertWeb.Endpoint.plug_builder_call/2
    (albert 0.1.0) deps/plug/lib/plug/debugger.ex:136: AlbertWeb.Endpoint."call (overridable 3)"/2
    (albert 0.1.0) lib/albert_web/endpoint.ex:1: AlbertWeb.Endpoint.call/2
    (phoenix 1.7.11) lib/phoenix/endpoint/sync_code_reload_plug.ex:22: Phoenix.Endpoint.SyncCodeReloadPlug.do_call/4
    (bandit 1.2.0) lib/bandit/pipeline.ex:101: Bandit.Pipeline.call_plug/2
    (bandit 1.2.0) lib/bandit/pipeline.ex:22: Bandit.Pipeline.run/6
    (bandit 1.2.0) lib/bandit/http1/handler.ex:33: Bandit.HTTP1.Handler.handle_data/3
    (bandit 1.2.0) lib/bandit/delegating_handler.ex:18: Bandit.DelegatingHandler.handle_data/3
    (bandit 1.2.0) /Users/xanderio/dev/cyberus/albert/deps/thousand_island/lib/thousand_island/handler.ex:379: Bandit.DelegatingHandler.handle_info/2
    (stdlib 4.3.1.3) gen_server.erl:1123: :gen_server.try_dispatch/4
```

**Comment by danschultzer** [comment]
Thanks, it has been resolved in v0.4.18!
